// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/debug.proto

package tensorflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// EXPERIMENTAL. Option for watching a node.
type DebugTensorWatch struct {
	// Name of the node to watch.
	NodeName string `protobuf:"bytes,1,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	// Output slot to watch.
	// The semantics of output_slot == -1 is that the node is only watched for
	// completion, but not for any output tensors. See NodeCompletionCallback
	// in debug_gateway.h.
	// TODO(cais): Implement this semantics.
	OutputSlot int32 `protobuf:"varint,2,opt,name=output_slot,json=outputSlot" json:"output_slot,omitempty"`
	// Name(s) of the debugging op(s).
	// One or more than one probes on a tensor.
	// e.g., {"DebugIdentity", "DebugNanCount"}
	DebugOps []string `protobuf:"bytes,3,rep,name=debug_ops,json=debugOps" json:"debug_ops,omitempty"`
	// URL(s) for debug targets(s).
	//
	// Supported URL formats are:
	//   - file:///foo/tfdbg_dump: Writes out Event content to file
	//     /foo/tfdbg_dump.  Assumes all directories can be created if they don't
	//     already exist.
	//   - grpc://localhost:11011: Sends an RPC request to an EventListener
	//     service running at localhost:11011 with the event.
	//   - memcbk:///event_key: Routes tensors to clients using the
	//     callback registered with the DebugCallbackRegistry for event_key.
	//
	// Each debug op listed in debug_ops will publish its output tensor (debug
	// signal) to all URLs in debug_urls.
	//
	// N.B. Session::Run() supports concurrent invocations of the same inputs
	// (feed keys), outputs and target nodes. If such concurrent invocations
	// are to be debugged, the callers of Session::Run() must use distinct
	// debug_urls to make sure that the streamed or dumped events do not overlap
	// among the invocations.
	// TODO(cais): More visible documentation of this in g3docs.
	DebugUrls []string `protobuf:"bytes,4,rep,name=debug_urls,json=debugUrls" json:"debug_urls,omitempty"`
	// Do not error out if debug op creation fails (e.g., due to dtype
	// incompatibility). Instead, just log the failure.
	TolerateDebugOpCreationFailures bool `protobuf:"varint,5,opt,name=tolerate_debug_op_creation_failures,json=tolerateDebugOpCreationFailures" json:"tolerate_debug_op_creation_failures,omitempty"`
}

func (m *DebugTensorWatch) Reset()                    { *m = DebugTensorWatch{} }
func (m *DebugTensorWatch) String() string            { return proto.CompactTextString(m) }
func (*DebugTensorWatch) ProtoMessage()               {}
func (*DebugTensorWatch) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *DebugTensorWatch) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *DebugTensorWatch) GetOutputSlot() int32 {
	if m != nil {
		return m.OutputSlot
	}
	return 0
}

func (m *DebugTensorWatch) GetDebugOps() []string {
	if m != nil {
		return m.DebugOps
	}
	return nil
}

func (m *DebugTensorWatch) GetDebugUrls() []string {
	if m != nil {
		return m.DebugUrls
	}
	return nil
}

func (m *DebugTensorWatch) GetTolerateDebugOpCreationFailures() bool {
	if m != nil {
		return m.TolerateDebugOpCreationFailures
	}
	return false
}

// EXPERIMENTAL. Options for initializing DebuggerState.
type DebugOptions struct {
	// Debugging options
	DebugTensorWatchOpts []*DebugTensorWatch `protobuf:"bytes,4,rep,name=debug_tensor_watch_opts,json=debugTensorWatchOpts" json:"debug_tensor_watch_opts,omitempty"`
	// Caller-specified global step count.
	// Note that this is distinct from the session run count and the executor
	// step count.
	GlobalStep int64 `protobuf:"varint,10,opt,name=global_step,json=globalStep" json:"global_step,omitempty"`
}

func (m *DebugOptions) Reset()                    { *m = DebugOptions{} }
func (m *DebugOptions) String() string            { return proto.CompactTextString(m) }
func (*DebugOptions) ProtoMessage()               {}
func (*DebugOptions) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *DebugOptions) GetDebugTensorWatchOpts() []*DebugTensorWatch {
	if m != nil {
		return m.DebugTensorWatchOpts
	}
	return nil
}

func (m *DebugOptions) GetGlobalStep() int64 {
	if m != nil {
		return m.GlobalStep
	}
	return 0
}

type DebuggedSourceFile struct {
	// The host name on which a source code file is located.
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	// Path to the source code file.
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	// The timestamp at which the source code file is last modified.
	LastModified int64 `protobuf:"varint,3,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	// Byte size of the file.
	Bytes int64 `protobuf:"varint,4,opt,name=bytes" json:"bytes,omitempty"`
	// Line-by-line content of the source code file.
	Lines []string `protobuf:"bytes,5,rep,name=lines" json:"lines,omitempty"`
}

func (m *DebuggedSourceFile) Reset()                    { *m = DebuggedSourceFile{} }
func (m *DebuggedSourceFile) String() string            { return proto.CompactTextString(m) }
func (*DebuggedSourceFile) ProtoMessage()               {}
func (*DebuggedSourceFile) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *DebuggedSourceFile) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DebuggedSourceFile) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *DebuggedSourceFile) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *DebuggedSourceFile) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *DebuggedSourceFile) GetLines() []string {
	if m != nil {
		return m.Lines
	}
	return nil
}

type DebuggedSourceFiles struct {
	// A collection of source code files.
	SourceFiles []*DebuggedSourceFile `protobuf:"bytes,1,rep,name=source_files,json=sourceFiles" json:"source_files,omitempty"`
}

func (m *DebuggedSourceFiles) Reset()                    { *m = DebuggedSourceFiles{} }
func (m *DebuggedSourceFiles) String() string            { return proto.CompactTextString(m) }
func (*DebuggedSourceFiles) ProtoMessage()               {}
func (*DebuggedSourceFiles) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *DebuggedSourceFiles) GetSourceFiles() []*DebuggedSourceFile {
	if m != nil {
		return m.SourceFiles
	}
	return nil
}

func init() {
	proto.RegisterType((*DebugTensorWatch)(nil), "tensorflow.DebugTensorWatch")
	proto.RegisterType((*DebugOptions)(nil), "tensorflow.DebugOptions")
	proto.RegisterType((*DebuggedSourceFile)(nil), "tensorflow.DebuggedSourceFile")
	proto.RegisterType((*DebuggedSourceFiles)(nil), "tensorflow.DebuggedSourceFiles")
}

func init() { proto.RegisterFile("tensorflow/core/protobuf/debug.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdd, 0x8a, 0x13, 0x31,
	0x14, 0x80, 0x89, 0xdd, 0x4a, 0x7b, 0x5a, 0x41, 0xe2, 0x82, 0x03, 0xfe, 0xec, 0xd0, 0xf5, 0xa2,
	0x17, 0xd2, 0x82, 0x3e, 0x81, 0xeb, 0xb2, 0x57, 0xea, 0x96, 0xa9, 0xa2, 0x77, 0x21, 0xd3, 0x39,
	0xd3, 0x0e, 0xa6, 0x73, 0x42, 0x72, 0x86, 0xe2, 0xbd, 0xcf, 0xe0, 0xc3, 0xf9, 0x24, 0x5e, 0x4a,
	0x92, 0x59, 0xaa, 0xdb, 0xbb, 0x9c, 0xef, 0xfc, 0x25, 0x1f, 0x81, 0x57, 0x8c, 0xad, 0x27, 0x57,
	0x1b, 0x3a, 0x2c, 0x37, 0xe4, 0x70, 0x69, 0x1d, 0x31, 0x95, 0x5d, 0xbd, 0xac, 0xb0, 0xec, 0xb6,
	0x8b, 0x18, 0x4a, 0x38, 0x56, 0xcd, 0x7e, 0x0b, 0x78, 0x7c, 0x1d, 0x72, 0x9f, 0x23, 0xfb, 0xaa,
	0x79, 0xb3, 0x93, 0xcf, 0x60, 0xdc, 0x52, 0x85, 0xaa, 0xd5, 0x7b, 0xcc, 0x44, 0x2e, 0xe6, 0xe3,
	0x62, 0x14, 0xc0, 0x27, 0xbd, 0x47, 0x79, 0x01, 0x13, 0xea, 0xd8, 0x76, 0xac, 0xbc, 0x21, 0xce,
	0x1e, 0xe4, 0x62, 0x3e, 0x2c, 0x20, 0xa1, 0xb5, 0x21, 0x0e, 0xdd, 0x71, 0x9b, 0x22, 0xeb, 0xb3,
	0x41, 0x3e, 0x08, 0xdd, 0x11, 0xdc, 0x5a, 0x2f, 0x5f, 0x00, 0xa4, 0x64, 0xe7, 0x8c, 0xcf, 0xce,
	0x62, 0x36, 0x95, 0x7f, 0x71, 0xc6, 0xcb, 0x0f, 0x70, 0xc9, 0x64, 0xd0, 0x69, 0x46, 0x75, 0x37,
	0x44, 0x6d, 0x1c, 0x6a, 0x6e, 0xa8, 0x55, 0xb5, 0x6e, 0x4c, 0xe7, 0xd0, 0x67, 0xc3, 0x5c, 0xcc,
	0x47, 0xc5, 0xc5, 0x5d, 0xe9, 0x75, 0x9a, 0xfe, 0xbe, 0xaf, 0xbb, 0xe9, 0xcb, 0x66, 0x3f, 0x05,
	0x4c, 0xfb, 0x5c, 0xe0, 0x5e, 0xae, 0xe1, 0x69, 0x9a, 0x9a, 0x0c, 0xa8, 0x43, 0x78, 0xae, 0x22,
	0xcb, 0xe9, 0x2a, 0x93, 0x37, 0xcf, 0x17, 0x47, 0x37, 0x8b, 0xfb, 0x5e, 0x8a, 0xf3, 0xea, 0x1e,
	0xb9, 0xb5, 0xec, 0x83, 0x90, 0xad, 0xa1, 0x52, 0x1b, 0xe5, 0x19, 0x6d, 0x06, 0xb9, 0x98, 0x0f,
	0x0a, 0x48, 0x68, 0xcd, 0x68, 0x67, 0xbf, 0x04, 0xc8, 0x38, 0x6b, 0x8b, 0xd5, 0x9a, 0x3a, 0xb7,
	0xc1, 0x9b, 0xc6, 0xa0, 0x94, 0x70, 0xb6, 0x23, 0xcf, 0xbd, 0xe0, 0x78, 0x0e, 0xee, 0xea, 0xc6,
	0xa0, 0xb2, 0x9a, 0x77, 0x51, 0xed, 0xb8, 0x18, 0x05, 0xb0, 0xd2, 0xbc, 0x93, 0x97, 0xf0, 0xc8,
	0x68, 0xcf, 0x6a, 0x4f, 0x55, 0x53, 0x37, 0x58, 0x65, 0x83, 0xb8, 0x6a, 0x1a, 0xe0, 0xc7, 0x9e,
	0xc9, 0x73, 0x18, 0x96, 0x3f, 0x18, 0xc3, 0x83, 0x42, 0x32, 0x05, 0x81, 0x9a, 0xa6, 0x8d, 0xe6,
	0x82, 0xf1, 0x14, 0xcc, 0xbe, 0xc1, 0x93, 0xd3, 0x7b, 0x79, 0xf9, 0x0e, 0xa6, 0x3e, 0x86, 0x2a,
	0xac, 0xf6, 0x99, 0x88, 0x6a, 0x5e, 0x9e, 0xa8, 0xf9, 0xaf, 0xad, 0x98, 0xf8, 0xe3, 0x88, 0xab,
	0xd7, 0x90, 0x91, 0xdb, 0xfe, 0xdb, 0x51, 0x3b, 0xbd, 0xc7, 0x03, 0xb9, 0xef, 0x57, 0x93, 0xd8,
	0xbc, 0x0a, 0x5f, 0xd1, 0xaf, 0xc4, 0x1f, 0x21, 0xca, 0x87, 0xf1, 0x5f, 0xbe, 0xfd, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x02, 0x64, 0x58, 0xbf, 0x02, 0x00, 0x00,
}
